# Generated by Django 5.0.5 on 2024-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='num_etudiant',
            field=models.IntegerField(default=-1),
        ),
    ]
