# Generated by Django 5.0.5 on 2024-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_etudiant_num_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='num_etudiant',
            field=models.CharField(max_length=15),
        ),
    ]
