# Generated by Django 5.0.5 on 2024-05-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_etudiant_num_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Etudiant'},
        ),
    ]
