# Generated by Django 5.0.5 on 2024-05-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_etudiant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Enseignant'},
        ),
        migrations.AlterModelOptions(
            name='professionnel',
            options={'verbose_name': 'Professionnel'},
        ),
        migrations.AlterModelOptions(
            name='tuteur',
            options={'verbose_name': 'Tuteur'},
        ),
    ]
