# Generated by Django 5.0.5 on 2024-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_admin_options_alter_enseignant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_connection',
            field=models.BooleanField(default=False),
        ),
    ]
