# Generated by Django 5.0.5 on 2024-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_customuser_first_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_connection',
            field=models.BooleanField(default=True),
        ),
    ]
