# Generated by Django 5.0.5 on 2024-05-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_customuser_first_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('profile', 'Profile'), ('autre_profil', 'Autre Profil')], default='profile', max_length=20),
        ),
    ]
