# Generated by Django 5.0.5 on 2024-05-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_customuser_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('Etudiant', 'Etudiant'), ('Admin', 'Admin'), ('Professionnel', 'Professionnel'), ('Tuteur', 'Tuteur')], default='Etudiant', max_length=20),
        ),
    ]
