# Generated by Django 5.0.5 on 2024-05-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_customuser_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_type',
            new_name='profile',
        ),
    ]
