# Generated by Django 5.0.5 on 2024-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_rename_profile_type_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('ENS', 'Enseignant'), ('ETU', 'Etudiant'), ('ADM', 'Admin'), ('PRO', 'Professionnel'), ('TUT', 'Tuteur')], default='Etudiant', max_length=3),
        ),
    ]
