# Generated by Django 5.0.5 on 2024-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('ENS', 'Enseignant'), ('ETU', 'Etudiant'), ('ADM', 'Admin'), ('PRO', 'Professionnel'), ('TUT', 'Tuteur')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stage',
            name='confidentiel',
            field=models.BooleanField(default=False),
        ),
    ]
