# Generated by Django 5.0.5 on 2024-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_alter_customuser_profile_alter_stage_confidentiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='heure_soutenance',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
