# Generated by Django 5.0.5 on 2024-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_alter_soutenance_heure_soutenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='stage',
            name='nom_entreprise',
            field=models.CharField(default='entreprise', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
