# Generated by Django 5.0.5 on 2024-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_alter_codepassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='salle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
