# Generated by Django 5.0.5 on 2024-05-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_jury_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='back.promo'),
        ),
    ]
