# Generated by Django 5.0.5 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_alter_etudiant_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='batiment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jury',
            name='campus',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jury',
            name='zoom',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
