# Generated by Django 5.0.5 on 2024-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_jury_batiment_jury_campus_jury_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='note',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jury',
            name='batiment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jury',
            name='campus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jury',
            name='salle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jury',
            name='zoom',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
