# Generated by Django 5.0.5 on 2024-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_soutenance_note_alter_jury_batiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='date_soutenance',
            field=models.DateField(),
        ),
    ]
