# Generated by Django 5.0.5 on 2024-06-10 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_alter_soutenance_date_soutenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date_naissance',
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='note',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
