# Generated by Django 5.0.5 on 2024-06-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_remove_etudiant_date_naissance_alter_soutenance_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='stage',
            name='etudiant',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='back.etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='num_etudiant',
            field=models.CharField(max_length=20),
        ),
    ]
