# Generated by Django 5.0.6 on 2024-06-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_remove_soutenance_etudiant_stage_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='stage',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='etudiant',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='back.etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='back.etudiant'),
        ),
    ]
