# Generated by Django 5.0.6 on 2024-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_remove_soutenance_stage_soutenance_etudiant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soutenance',
        ),
    ]
