# Generated by Django 5.0.5 on 2024-06-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_remove_soutenance_stage_soutenance_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='back.etudiant'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='back.etudiant'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.tuteur'),
        ),
    ]
