# Generated by Django 5.0.6 on 2024-06-26 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_delete_soutenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soutenance', models.DateField()),
                ('heure_soutenance', models.TimeField(default=None)),
                ('note', models.FloatField(validators=[django.core.validators.MaxValueValidator(20.0)])),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='back.etudiant')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.jury')),
            ],
        ),
    ]
