# Generated by Django 5.0.6 on 2024-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_soutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='date_soutenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='heure_soutenance',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
