# Generated by Django 5.0.6 on 2024-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0030_alter_soutenance_jury_alter_soutenance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='num_etudiant',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
