# Generated by Django 5.0.6 on 2024-06-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0031_alter_etudiant_num_etudiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
