# Generated by Django 5.0.6 on 2024-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0034_alter_stage_nom_entreprise'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['num_etudiant'], name='back_etudia_num_etu_8d4686_idx'),
        ),
    ]
