# Generated by Django 5.0.6 on 2024-06-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('back', '0035_etudiant_back_etudia_num_etu_8d4686_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='back_custom_email_3ad21a_idx'),
        ),
    ]
