# Generated by Django 5.0.6 on 2024-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0036_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jury',
            name='num_jury',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
