# Generated by Django 5.0.6 on 2024-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0037_filiere_is_active_jury_num_jury'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
