# Generated by Django 5.0.6 on 2024-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0040_stage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
