# Generated by Django 5.0.6 on 2024-06-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0041_soutenance_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='nom_directeur',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='prenom_directeur',
        ),
    ]
