# Generated by Django 5.0.6 on 2024-06-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0043_rename_enseignant_membrejury_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('membrejury_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.membrejury')),
            ],
            options={
                'verbose_name': 'Enseignant',
            },
            bases=('back.membrejury',),
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('membrejury_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.membrejury')),
            ],
            options={
                'verbose_name': 'Professionnel',
            },
            bases=('back.membrejury',),
        ),
    ]
