# Generated by Django 5.0.6 on 2024-06-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0044_enseignant_professionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='leader',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='back.membrejury'),
            preserve_default=False,
        ),
    ]
