# Generated by Django 5.0.6 on 2024-06-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0045_jury_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='back.membrejury'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.etudiant'),
        ),
    ]
