# Generated by Django 5.0.6 on 2024-07-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0046_alter_jury_leader_alter_soutenance_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='promo',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=100)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.filiere')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sessions',
            field=models.ManyToManyField(to='back.session'),
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
