# Generated by Django 5.0.6 on 2024-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0047_remove_etudiant_promo_session_etudiant_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='soutenu',
            field=models.BooleanField(default=False),
        ),
    ]
