# Generated by Django 5.0.6 on 2024-07-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0048_soutenance_soutenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='leader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='back.membrejury'),
        ),
    ]
