# Generated by Django 5.0.6 on 2024-07-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0049_alter_jury_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='stage',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='back.stage'),
            preserve_default=False,
        ),
    ]
