# Generated by Django 5.0.6 on 2024-07-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0050_remove_soutenance_etudiant_soutenance_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='sessions',
        ),
        migrations.AddField(
            model_name='jury',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='back.session'),
            preserve_default=False,
        ),
    ]
