# Generated by Django 5.0.6 on 2024-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0051_remove_etudiant_sessions_jury_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='soutenu',
            field=models.BooleanField(default=False),
        ),
    ]
