# Generated by Django 5.0.6 on 2024-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0052_stage_soutenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='num_convention',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
