# Generated by Django 5.0.6 on 2024-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0053_stage_num_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='num_convention',
            field=models.IntegerField(unique=True),
        ),
    ]
