# Generated by Django 5.0.6 on 2024-07-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0054_alter_stage_num_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.filiere'),
        ),
    ]
