# Generated by Django 5.0.6 on 2024-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0055_admin_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='session',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('ENS', 'Enseignant'), ('ETU', 'Etudiant'), ('ADM', 'Admin'), ('PRO', 'Professionnel'), ('TUT', 'Tuteur'), ('SPR', 'Super_user')], max_length=3),
        ),
    ]
