# Generated by Django 5.0.6 on 2024-07-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0056_remove_jury_session_alter_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='back.session'),
            preserve_default=False,
        ),
    ]
