# Generated by Django 5.0.6 on 2024-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0057_jury_session'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('nom', 'filiere'), name='nom_filiere'),
        ),
    ]
