# Generated by Django 5.0.6 on 2024-07-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0059_jury_num_jury_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='back.stage'),
        ),
    ]
