# Generated by Django 5.0.6 on 2024-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0060_alter_soutenance_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fini',
            field=models.BooleanField(default=False),
        ),
    ]
