# Generated by Django 5.0.6 on 2024-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0061_session_fini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='soutenu',
        ),
    ]
