# Generated by Django 5.0.6 on 2024-07-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0062_remove_stage_soutenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='back.stage'),
        ),
    ]
