# Generated by Django 5.0.6 on 2024-07-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0065_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='fini',
        ),
    ]
