# Generated by Django 5.0.6 on 2024-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0066_remove_session_fini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='status',
            new_name='statusSession',
        ),
    ]
