# Generated by Django 5.0.6 on 2024-05-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulaires',
            new_name='Formulaire',
        ),
    ]
