# Generated by Django 5.0.6 on 2024-05-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_rename_formulaires_formulaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
