# Generated by Django 5.0.6 on 2024-05-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_alter_formulaire_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='uid',
        ),
        migrations.AddField(
            model_name='response',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('paragraphe', 'paragraphe'), ('checkbox', 'checkbox'), ('dropdown', 'dropdown')], max_length=15),
        ),
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaire.question')),
            ],
        ),
    ]
