# Generated by Django 5.0.6 on 2024-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0004_remove_formulaire_uid_response_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='formulaires',
            new_name='formulaire',
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
