# Generated by Django 5.0.5 on 2024-05-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0005_rename_formulaires_question_formulaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='formulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='formulaire.formulaire'),
        ),
    ]
