# Generated by Django 5.0.5 on 2024-05-29 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0006_alter_question_formulaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbox', to='formulaire.question'),
        ),
    ]
