# Generated by Django 5.0.6 on 2024-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0007_alter_checkbox_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaire',
            old_name='title',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='formulaire',
            name='profile',
            field=models.CharField(choices=[('FR', 'Français'), ('AN', 'Anglais')], default='ETU', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
