# Generated by Django 5.0.6 on 2024-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0008_rename_title_formulaire_titre_formulaire_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='langue',
            field=models.CharField(choices=[('FR', 'Français'), ('AN', 'Anglais')], default='FR', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='profile',
            field=models.CharField(choices=[('ENS', 'Enseignant'), ('ETU', 'Etudiant'), ('JUR', 'Jury')], max_length=3),
        ),
    ]
