# Generated by Django 5.0.6 on 2024-06-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0044_enseignant_professionnel'),
        ('formulaire', '0010_remove_response_user_response_id_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='filiere',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='back.filiere'),
            preserve_default=False,
        ),
    ]
