# Generated by Django 5.0.6 on 2024-06-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0011_formulaire_filiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='titre',
        ),
    ]
