# Generated by Django 5.0.6 on 2024-06-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0014_question_obligatoire_responsecheckbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseCheckbox',
        ),
    ]
