# Generated by Django 5.0.6 on 2024-06-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0044_enseignant_professionnel'),
        ('formulaire', '0015_delete_responsecheckbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCheckbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaire.checkbox')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.etudiant')),
            ],
        ),
    ]
