# Generated by Django 5.0.6 on 2024-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0016_responsecheckbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='profile',
            field=models.CharField(choices=[('TUT', 'Tuteur'), ('ETU', 'Etudiant'), ('JUR', 'Jury')], max_length=3),
        ),
    ]
