# Generated by Django 5.0.6 on 2024-07-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0017_alter_formulaire_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='statusFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('envoie', 'envoie'), ('sauvegarde', 'sauvegarde'), ('rendu', 'rendu')], default='envoie', max_length=15)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaire.formulaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
