# Generated by Django 5.0.6 on 2024-07-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0047_remove_etudiant_promo_session_etudiant_sessions_and_more'),
        ('formulaire', '0018_statusformulaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='filiere',
        ),
        migrations.AddField(
            model_name='formulaire',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.session'),
        ),
    ]
