# Generated by Django 5.0.6 on 2024-07-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0047_remove_etudiant_promo_session_etudiant_sessions_and_more'),
        ('formulaire', '0019_remove_formulaire_filiere_formulaire_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='back.session'),
            preserve_default=False,
        ),
    ]
