# Generated by Django 5.0.6 on 2024-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0020_alter_formulaire_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='content',
            field=models.BooleanField(default=False),
        ),
    ]
