# Generated by Django 5.0.6 on 2024-07-03 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0021_checkbox_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusformulaire',
            unique_together={('formulaire', 'user')},
        ),
    ]
