# Generated by Django 5.0.6 on 2024-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0022_alter_statusformulaire_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusformulaire',
            old_name='status',
            new_name='statusForm',
        ),
    ]
