# Generated by Django 5.0.6 on 2024-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0023_rename_status_statusformulaire_statusform'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecheckbox',
            name='valeur',
            field=models.BooleanField(default=False),
        ),
    ]
