# Generated by Django 5.0.6 on 2024-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0024_responsecheckbox_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='soutenu',
            field=models.BooleanField(default=False),
        ),
    ]
