# Generated by Django 5.0.6 on 2024-07-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0025_formulaire_soutenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='soutenu',
        ),
    ]
