# Generated by Django 5.0.6 on 2024-07-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0052_stage_soutenu'),
        ('formulaire', '0026_remove_formulaire_soutenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecheckbox',
            name='id_etudiant',
        ),
        migrations.RemoveField(
            model_name='responseform',
            name='id_etudiant',
        ),
        migrations.AddField(
            model_name='responsecheckbox',
            name='id_stage',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='back.stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responseform',
            name='id_stage',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='back.stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusformulaire',
            name='stage',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='back.stage'),
            preserve_default=False,
        ),
    ]
