# Generated by Django 5.0.6 on 2024-07-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0027_remove_responsecheckbox_id_etudiant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsecheckbox',
            old_name='id_stage',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='responseform',
            old_name='id_stage',
            new_name='stage',
        ),
    ]
