# Generated by Django 5.0.6 on 2024-07-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0028_rename_id_stage_responsecheckbox_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='titre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='titre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='responseform',
            name='content',
            field=models.TextField(),
        ),
    ]
