# Generated by Django 5.0.6 on 2024-07-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0063_alter_soutenance_stage'),
        ('formulaire', '0029_alter_formulaire_titre_alter_question_titre_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='responseform',
            constraint=models.UniqueConstraint(fields=('question', 'stage'), name='question_session'),
        ),
    ]
