# Generated by Django 5.0.6 on 2024-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0063_alter_soutenance_stage'),
        ('formulaire', '0030_responseform_question_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responseform',
            name='question_session',
        ),
        migrations.AddConstraint(
            model_name='responsecheckbox',
            constraint=models.UniqueConstraint(fields=('checkbox', 'stage'), name='checkbox_stage'),
        ),
        migrations.AddConstraint(
            model_name='responseform',
            constraint=models.UniqueConstraint(fields=('question', 'stage'), name='question_stage'),
        ),
    ]
