# Generated by Django 5.0.6 on 2024-07-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0032_formulaire_date_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox',
            name='content',
        ),
    ]
