# Generated by Django 5.0.6 on 2024-07-26 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0066_remove_session_fini'),
        ('formulaire', '0033_remove_checkbox_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusformulaire',
            unique_together={('formulaire', 'user', 'stage')},
        ),
    ]
