# Generated by Django 5.0.6 on 2024-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=400)),
                ('contenu', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
